# Generated by Django 3.2.9 on 2021-11-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
